spring.application.name=loja-produtos
# Conexão com o Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/ProdutosJava
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:sua_senha_local_aqui}

# Configuração do Hibernate (ORM equivalente ao Mongoose/Prisma)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
